### ISSUE TITLE
GTK theme (Client Side Decorations) do not match Server Side Decorations.

### ISSUE THREAD

**Issue by ryanrms** [darkomarko42/Linea#1]
Hi! I l really like your theme.  One thing I noticed after trying it is that GTKHeaderBar applications (using Client Side Decorations sourced from the GTK theme) do not match the Server Side Decorations (normal Muffin window decorations on Cinnamon).  It seems that the GTK theme still inherits window decorations from the theme it was based on.  If you could update the GTK theme with the decorations that would be great!

I should note that this issue effects both the Maximize and Minimize buttons, but you can't see the former in this screenshot.
![Screenshot from 2021-12-13 14-07-25](https://user-images.githubusercontent.com/2936638/145889265-6f46cdb7-91da-48b3-ae44-05518638cb2d.png)

**Comment by darkomarko42** [comment]
The shadows of metacity themes(muffin) are set by cinnamon DE. i cannot change that, you could try set yours using an extension for cinnamon call "user shadows" or something like that :)

**Comment by ryanrms** [comment]
The shadows don't worry me, it's the Maximize and Minimize buttons.  See how the minimize button on the GTKheaderbar application looks like an Arrow pointing down with a line below it?  If you could make it match the single "underscore" minimize button which looks much nicer.  It is set by the GTK theme.

For example, with the GTK theme set to something else and the Window decorations set to Linea, the GTKHeaderBar apps use the GTK theme decorations, like in this example:
![Uploading Screenshot from 2021-12-13 14-28-59.png…]()

**Comment by darkomarko42** [comment]
Oh i get it... Im using the classic "windows" style because most of icons pack are using that. You can change it by going the metacity-1/assets/ and then change the svg files. Open with inkscape, paste the minimize and maximize and change the hex color with the original icon
